### ISSUE TITLE
Issue with creating new team

### ISSUE THREAD

**Issue by oryan** [brettdoyle44/redwoodjs-saas-starter#1]
As a brand new user I am getting the following error on the form when trying to create a team:
``` 
Variable "$id" of required type "String!" was not provided.
```

In the command line I am seeing this error:
```
api | 03:05:41 🐛        operationName:
api | 03:05:41 🐛        variables:
api | 03:05:41 🐛 graphql-server GraphQL execution started: CreateTeamMutation
api | 03:05:41 🐛 Execution end
api | 03:05:41 🐛        result:
api | 03:05:41 🚨 graphql-server Variable "$id" of required type "String!" was not provided. 
api |
api | 🚨 GraphQLError Info
api |
api | {
api |   "locations": [
api |     {
api |       "line": 1,
api |       "column": 55
api |     }
api |   ],
api |   "extensions": {}
api | }
api |
api | 🥞 Error Stack
api |
api | GraphQLError: Variable "$id" of required type "String!" was not provided.
api |     at coerceVariableValues (C:\.. ..\App Dev\waveform\node_modules\graphql\execution\values.js:105:11)        
api |     at getVariableValues (C:\.. ..\App Dev\waveform\node_modules\graphql\execution\values.js:45:21)
api |     at buildExecutionContext (C:\.. ..\App Dev\waveform\node_modules\graphql\execution\execute.js:280:63)      
api |     at execute (C:\.. ..\App Dev\waveform\node_modules\graphql\execution\execute.js:116:22)
api |     at C:\.. ..\node_modules\@envelop\core\cjs\orchestrator.js:379:33
api |     at async processRequest (C:\.. ..\App Dev\waveform\node_modules\@graphql-yoga\common\index.js:194:20)      
api |     at async YogaServer.getResponse (C:\.. ..\App Dev\waveform\node_modules\@graphql-yoga\common\index.js:909:28)
api |     at async YogaServer.handleRequest (C:\.. ..\App Dev\waveform\node_modules\@graphql-yoga\common\index.js:671:30)
api |     at async handlerFn (C:\.. ..\App Dev\waveform\node_modules\@redwoodjs\graphql-server\dist\functions\graphql.js:271:24)
api |     at async execFn (C:\.. ..\node_modules\@redwoodjs\graphql-server\dist\functions\graphql.js:310:16)
```

### Steps to reproduce:
1. ✅ Fresh pull from Github
2. ✅ Follow instructions to setup and run successfully
3. ✅ View in browser and create new account
4. ✅ Receive Supabase magic link email and click it
5. ✅ Successfully login and see the create a new team form
6. ❌ Fill out Team name and submit to create new team.

I've placed a few `console.log(currentUser.id)` in `CreateTeamForm.tsx` and `NewUserPage.tsx` and it always returns as `undefined`

Any help on figuring out what this might be would be super appreciated.

**Comment by oryan** [comment]
I'm not 100% what happened, 
But I restarted everything and it seems to be working now... Not sure what was different from the last 4 or 5 times, but everything seems to be working as expected.

I'm going to close this bug and If I figure out what happened I'll add more context incase this issue pops up in search and anyone else is dealing with it.

**Comment by brettdoyle44** [comment]
@oryan apologies on the delay in my response. I will say that I have not looked at this in a couple months. I am happy to hear that somehow this is still working haha. But I will probably do an update/work on a more production level version of this. This version was really just meant to be exploratory. With that said feel free to Fork the project and build off of it!

**Comment by oryan** [comment]
@brettdoyle44 It's been incredibly helpful to figure out multi-tenancy in Redwood. Massive thanks for sharing this publicly.
